---
- name: Import Icinga2 GPG Key
  rpm_key:
    state: present
    key:  https://packages.icinga.com/icinga.key
  become: yes

- name: Get Icinga2 Yum Repo on RedHat OS family
  yum:
    name: "{{ icinga2_url_yum }}"
    state: present
  become: yes

- name: Install Icinga Packages on RedHat OS family
  action: >
    {{ ansible_pkg_mgr }} name="{{ item }}-{{ icinga2_rhel_version }}" state=present update_cache=yes
  with_items: '{{ icinga2_yum }}'
  become: yes

- name: Install monitoring plugins
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=no
  with_items: '{{ icinga2_monitoring_plugins_rhel }}'
  become: yes

- name: Copy check_linux_memory
  copy:
    src: check_linux_memory
    dest: /usr/lib64/nagios/plugins
    group: root
    owner: root
    mode: 0755
  become: yes
