---
- name: Import Icinga2 GPG Key
  rpm_key:
    state: present
    key:  https://packages.icinga.com/icinga.key
  become: yes

- name: Get Icinga2 Yum Repo on RedHat OS family
  yum:
    name: "{{ icinga2_url_yum }}"
    state: present
  become: yes

- name: Install Icinga Packages on RedHat OS family
  yum:
    name: "{{ item }}"
  loop: "{{ icinga2_yum }}"
  become: yes

- name: Install yum-plugin-versionlock
  yum:
    name: yum-plugin-versionlock
  become: yes

- name: versionlock Icinga Packages on RedHat OS family
  command: yum versionlock "{{ item }}-{{ icinga2_rhel_version }}"
  loop: '{{ icinga2_yum }}'
  args:
    warn: false
  become: yes

- name: Install monitoring plugins
  yum:
    name: '{{ icinga2_monitoring_plugins_rhel }}'
    state: present
    update_cache: no
  become: yes

- name: Copy check_linux_memory
  copy:
    src: check_linux_memory
    dest: /usr/lib64/nagios/plugins
    group: root
    owner: root
    mode: 0755
  become: yes
